# coding: utf-8

# flake8: noqa

"""
    Task Management System API

    FastAPI Task Management Backend with strict state-machine transition rules. Task status can only change in strict sequential order: TODO -> IN_PROGRESS -> REVIEW -> DONE.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "HealthApi",
    "TasksApi",
    "WorkflowApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "HTTPValidationError",
    "LocationInner",
    "TaskCreate",
    "TaskResponse",
    "TaskStatusUpdate",
    "TaskUpdate",
    "ValidationError",
]

# import apis into sdk package
from task_management_sdk.api.health_api import HealthApi as HealthApi
from task_management_sdk.api.tasks_api import TasksApi as TasksApi
from task_management_sdk.api.workflow_api import WorkflowApi as WorkflowApi

# import ApiClient
from task_management_sdk.api_response import ApiResponse as ApiResponse
from task_management_sdk.api_client import ApiClient as ApiClient
from task_management_sdk.configuration import Configuration as Configuration
from task_management_sdk.exceptions import OpenApiException as OpenApiException
from task_management_sdk.exceptions import ApiTypeError as ApiTypeError
from task_management_sdk.exceptions import ApiValueError as ApiValueError
from task_management_sdk.exceptions import ApiKeyError as ApiKeyError
from task_management_sdk.exceptions import ApiAttributeError as ApiAttributeError
from task_management_sdk.exceptions import ApiException as ApiException

# import models into sdk package
from task_management_sdk.models.http_validation_error import HTTPValidationError as HTTPValidationError
from task_management_sdk.models.location_inner import LocationInner as LocationInner
from task_management_sdk.models.task_create import TaskCreate as TaskCreate
from task_management_sdk.models.task_response import TaskResponse as TaskResponse
from task_management_sdk.models.task_status_update import TaskStatusUpdate as TaskStatusUpdate
from task_management_sdk.models.task_update import TaskUpdate as TaskUpdate
from task_management_sdk.models.validation_error import ValidationError as ValidationError

