# coding: utf-8

"""
    Task Management System API

    FastAPI Task Management Backend with strict state-machine transition rules. Task status can only change in strict sequential order: TODO -> IN_PROGRESS -> REVIEW -> DONE.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from task_management_sdk.models.task_update import TaskUpdate

class TestTaskUpdate(unittest.TestCase):
    """TaskUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaskUpdate:
        """Test TaskUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaskUpdate`
        """
        model = TaskUpdate()
        if include_optional:
            return TaskUpdate(
                title = '0',
                description = '',
                status = '',
                priority = '',
                due_date = ''
            )
        else:
            return TaskUpdate(
        )
        """

    def testTaskUpdate(self):
        """Test TaskUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
