# coding: utf-8

"""
    Task Management System API

    FastAPI Task Management Backend with strict state-machine transition rules. Task status can only change in strict sequential order: TODO -> IN_PROGRESS -> REVIEW -> DONE.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from task_management_sdk.api.workflow_api import WorkflowApi


class TestWorkflowApi(unittest.TestCase):
    """WorkflowApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorkflowApi()

    def tearDown(self) -> None:
        pass

    def test_get_workflow_rules_api_workflow_rules_get(self) -> None:
        """Test case for get_workflow_rules_api_workflow_rules_get

        Get Workflow Rules
        """
        pass


if __name__ == '__main__':
    unittest.main()
